In [1]:
import pandas as pd

In [21]:
df = pd.read_csv('popular_cities_weather.csv', sep=',', na_values=[''], quotechar='"')
df

           date  tavg  tmin  tmax   prcp  wspd    pres     tsun    city
0      1/1/2020  24.9  19.2  29.9    0.0   NaN  1013.4  13800.0  Mumbai
1      2/1/2020  27.3  21.0  32.6    0.0   NaN  1012.7  11220.0  Mumbai
2      3/1/2020  27.7  22.6  31.9    0.0   NaN  1011.2  12900.0  Mumbai
3      4/1/2020  30.2  26.4  33.9    0.0   NaN  1009.6  14220.0  Mumbai
4      5/1/2020  31.1  28.6  34.0    0.0   NaN  1007.3  15960.0  Mumbai
...         ...   ...   ...   ...    ...   ...     ...      ...     ...
7051   8/1/2025  20.8  18.0  24.8  321.1   NaN  1007.4      NaN  Shimla
7052   9/1/2025  19.8  16.3  24.3  150.9   NaN  1009.4      NaN  Shimla
7053  10/1/2025  15.9  10.6  22.6   61.5   NaN  1015.1      NaN  Shimla
7054  11/1/2025  11.6   6.1  19.4    2.4   NaN  1017.8      NaN  Shimla
7055  12/1/2025  10.9   6.4  18.3    0.0   NaN  1017.9      NaN  Shimla

[7056 rows x 9 columns]

In [22]:
df.drop('wspd',axis=1, inplace= True)

In [23]:
df.size

56448

In [26]:
df.shape

(2402, 8)

In [25]:
df.dropna(inplace=True)

In [27]:
df

           date  tavg  tmin  tmax   prcp    pres     tsun        city
0      1/1/2020  24.9  19.2  29.9    0.0  1013.4  13800.0      Mumbai
1      2/1/2020  27.3  21.0  32.6    0.0  1012.7  11220.0      Mumbai
2      3/1/2020  27.7  22.6  31.9    0.0  1011.2  12900.0      Mumbai
3      4/1/2020  30.2  26.4  33.9    0.0  1009.6  14220.0      Mumbai
4      5/1/2020  31.1  28.6  34.0    0.0  1007.3  15960.0      Mumbai
...         ...   ...   ...   ...    ...     ...      ...         ...
6691   8/1/2025  29.0  26.7  31.3  284.0  1003.2   6000.0  Maheshtala
6692   9/1/2025  29.8  27.1  32.5  465.0  1004.5   7740.0  Maheshtala
6693  10/1/2025  28.6  25.3  31.9  289.0  1009.7   9180.0  Maheshtala
6694  11/1/2025  24.0  19.4  28.7    0.0  1013.6  11520.0  Maheshtala
6695  12/1/2025  19.7  15.3  24.1    0.0  1015.7   5460.0  Maheshtala

[2402 rows x 8 columns]

In [28]:
df.to_csv('cleaned_pcw_dataset.csv')